dataDaily <- dataUptodate
nExamples <- examplesToGenerate
nLags <- lagToApply
nLags <- 14
i <- 1
testDateStart <- as_date("2021-01-01")  # oldest date we assume to avoid too old simulations
startDateDataset <- as_date("2015-01-01")  # oldest available date for training

sampleDates <- sort(sample(as_date(c(testDateStart:(max(dataDaily$date)-nLags))), nExamples, replace=FALSE))
recommendationsConsolidated <- data.frame()  # initialize
i <- sampleDates[1]
# build dataset of all past observations (time series) until given date
print(paste0("Processing date: ", as_date(i), " | Horizon: ",nLags))
lastDateAvailable <- as_date(i) # last date available for training observations
firstDateToForecast <- lastDateAvailable + 1
lastDateToForecast <- firstDateToForecast + nLags - 1


# *****
laggedVbles <- c("VIX_n", "VVIX_n", "VIX3M_n", "VIXNsdq_n", "GoldVlty_n")
calendarVbles <- c("month", "dayInMonth", "wkDay", "yrWeek")
dataDaily <- dataDaily %>% mutate(
  VIX_n = lag(VIX, n=nLags),
  VVIX_n = lag(VVIX, n=nLags),
  VIX3M_n = lag(VIX3M, n=nLags),
  VIXNsdq_n = lag(VIXNsdq, n=nLags),
  GoldVlty_n = lag(GoldVlty, n=nLags)
)
text_regressors <- "VX+C2"
# prepare training dataset (past)
dataDailyPastRefDate <- dataDaily %>%
  select(date, VIX, all_of(laggedVbles), all_of(calendarVbles)) %>%
  filter(date >= (startDateDataset+nLags+1) & date <= lastDateAvailable)  # we remove lines with NAs generated by lagging
# calculate regressors (future)
futureData <- dataDaily %>%
  select(date, all_of(laggedVbles), all_of(calendarVbles)) %>%
  filter(date >= firstDateToForecast & date <= lastDateToForecast)

# forecast obtained data into the short future
yTrain <- dataDailyPastRefDate$VIX
xTrain <- dataDailyPastRefDate[,(3:length(dataDailyPastRefDate))]  # remove date and VIX
print(paste("Regressors used by NN:")); print(paste(names(xTrain)))
print(paste("yTrain:", length(yTrain), "frequency: ", frequencyNN))

# fit6 <- nnetar(ts(yTrain, frequency = frequencyNN), xreg = xTrain)
fit6 <- nnetar(ts(yTrain, frequency = frequencyNN), xreg = xTrain, MaxNWts=2000)
summary(fit6)
# forecast
xFuture <- futureData[,-1] # remove date
# fc6 <- forecast(fit6, h = nLags, xreg = xFuture, PI = F)
fc6 <- forecast(fit6, h = nLags, xreg = xFuture, PI = F)
summary(fc6)
