#========================================================
# Function to generate recommendations for n "examplesToGenerate" dates
# https://bookdown.org/singh_pratap_tejendra/intro_time_series_r/neural-networks-in-time-series-analysis.html
generateRecommendations <- function(dataDaily, nExamples, nLags) {
  testDateStart <- as_date("2021-01-01")  # oldest date we assume to avoid too old simulations
  startDateDataset <- as_date("2015-01-01")  # oldest available date for training
  # determine vector of dates to generate. If 0, then: today
  if (nExamples == 0) {
    sampleDates <- as_date(Sys.time())
  } else {
    sampleDates <- sort(sample(as_date(c(testDateStart:(max(dataDaily$date)-nLags))), nExamples, replace=FALSE))
  }
  recommendationsConsolidated <- data.frame()  # initialize
  for (i in sampleDates) {
    # build dataset of all past observations (time series) until given date
    print(paste0("Processing date: ", as_date(i), " | Horizon: ",nLags))
    lastDateAvailable <- as_date(i) # last date available for training observations
    firstDateToForecast <- lastDateAvailable + 1
    lastDateToForecast <- firstDateToForecast + nLags - 1

    laggedVbles <- c("VIX_n", "VVIX_n", "VIX3M_n", "VIXNsdq_n", "GoldVlty_n", 
                     "VIX_n2", "VVIX_n2", "VIX3M_n2", "VIXNsdq_n2", "GoldVlty_n2")
    calendarVbles <- c("month", "dayInMonth", "wkDay", "yrWeek")
    dataDaily <- dataDaily %>% mutate(
      VIX_n = lag(VIX, n=nLags),
      VVIX_n = lag(VVIX, n=nLags),
      VIX3M_n = lag(VIX3M, n=nLags),
      VIXNsdq_n = lag(VIXNsdq, n=nLags),
      GoldVlty_n = lag(GoldVlty, n=nLags),
      VIX_n2 = lag(VIX, n=nLags+1),
      VVIX_n2 = lag(VVIX, n=nLags+1),
      VIX3M_n2 = lag(VIX3M, n=nLags+1),
      VIXNsdq_n2 = lag(VIXNsdq, n=nLags+1),
      GoldVlty_n2 = lag(GoldVlty, n=nLags+1)
    )
    text_regressors <- "VX+VN2+C2"
    
    # prepare forecast dataset (past)
    dataDailyPastRefDate <- dataDaily %>%
      select(date, VIX, all_of(laggedVbles), all_of(calendarVbles)) %>%
      filter(date >= (startDateDataset+nLags+1) & date <= lastDateAvailable)  # we remove lines with NAs generated by lagging
    # calculate regressors (future)
    futureData <- dataDaily %>%
      select(date, all_of(laggedVbles), all_of(calendarVbles)) %>%
      filter(date >= firstDateToForecast & date <= lastDateToForecast)

    # NN and forecast obtained data into the short future
    yTrain <- dataDailyPastRefDate$VIX
    xTrain <- dataDailyPastRefDate[,(3:length(dataDailyPastRefDate))]  # remove date and VIX
    print(paste("Regressors used by NN:")); print(paste(names(xTrain)))
    print(paste("yTrain:", length(yTrain), "frequency: ", frequencyNN))
    
    fit6 <- nnetar(ts(yTrain, frequency = frequencyNN), xreg = xTrain, MaxNWts=2000)
    # forecast
    xFuture <- futureData[,-1] # remove date
    fc6 <- forecast(fit6, h = nLags, xreg = xFuture, PI = F)
    
    # store
    VIX_forecasted <- fc6$mean
    # calculate accuracy details
    closingRef <- dataDaily %>% filter(date == lastDateAvailable) %>% select(date, VIX)
    real <- dataDaily %>% filter(between(date,firstDateToForecast,lastDateToForecast)) %>% select(date,VIX_real=VIX)
    recommendationsForDate_NN <- 
      cbind(date_txn=closingRef$date, VIX_txn=closingRef$VIX, real, VIX_forecasted = as.numeric(VIX_forecasted)) %>% 
      mutate(
        realChangePercent = 100*(VIX_real - VIX_txn)/VIX_txn, 
        predChangePercent = as.numeric(100*(VIX_forecasted - VIX_txn)/VIX_txn), 
        txnLength = date - date_txn, 
        horizon = nLags, 
        action = as.character(ifelse(VIX_forecasted > VIX_txn, "BUY", "SELL")), 
        earningsPercent = as.numeric(
          ifelse
          (
            (realChangePercent * predChangePercent) > 0, 
            abs(realChangePercent), 
            -1*abs(realChangePercent)
          )
        ),       
        regressors = text_regressors,
        transformations = transformation, 
        length = length(yTrain), 
        success = as.logical(earningsPercent >= 0)
      )
    # show  
    matplot(recommendationsForDate_NN[,c(2, 4:5)], type = "b", pch=1, col = c(1, 3,2))
    legend("bottomleft", legend = c("VIX_txn", "VIX_real", "VIX_forecasted"), col= c(1, 3,2), pch=1)
    recommendationsConsolidated <- rbind(recommendationsConsolidated, recommendationsForDate_NN)
  }
  print("PROCESS FINISHED. Recommended actions generated based in all past values until run date")
  # consolidate new generated observations for history
  saveRDS((rbind(readRDS("project2_main/recommendationsNN_all.rds"), recommendationsConsolidated)), "project2_main/recommendationsNN_all.rds")
  return(recommendationsConsolidated)
}


